package com.linkedlist;

import java.util.ArrayList;
import java.util.List;

public class HMap {
	/*
	 * Implementing Manual HashMap
	 */
	
	public List<Element>[] array;
	
	//Constructor to initialize list
	public HMap(int size){
		array = new ArrayList[size];
		for(int i = 0;i<size; i++){
			array[i] =  new ArrayList<Element>();
		}
	}
	
	//Main Method
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		HMap h = new HMap(10);
		
		//Adding Values to list according to hash values generated by keys
		h.putValues(1,"1");
		h.putValues(101,"101");
		h.putValues(101,"102");
		h.putValues(201,"201");
		h.putValues(301,"301");
		h.putValues(401,"401");
		h.putValues(501,"501");
		h.putValues(2,"2");
		h.putValues(102,"102");
		h.putValues(202,"202");
		h.putValues(302,"302");
		h.putValues(402,"402");
		h.putValues(502,"502");
		
		//Printing Values
		h.printValues();
		
		//Removing Values by key
		h.removeValuesByKey(101);
		System.out.println();
		System.out.println("********After Removing Some Values: **********");
		h.printValues();
		
		//Getting values by key
		System.out.println();
		h.getValuesByKey(201);
	}


	private void getValuesByKey(int key) {
		// TODO Auto-generated method stub
		int hashcode = convertTOHasCode(key);
		List<Element> list = array[hashcode];
		
		for(int i=0; i<list.size(); i++){
			if(key == list.get(i).key)
				System.out.println("Value According to Key: " + list.get(i).value);
		}
	}

	private void removeValuesByKey(int key) {
		// TODO Auto-generated method stub
		int hashcode = convertTOHasCode(key);
		List<Element> list = array[hashcode];
		
		for(int i=0; i<list.size(); i++){
			if(key == list.get(i).key)
				list.remove(i);
		}
	}

	private void putValues(int key, String value) {
		// TODO Auto-generated method stub
		int hascode = convertTOHasCode(key);
		List<Element> list = array[hascode];
		Element e = new Element();
		e.value = value;
		e.key = key;
		boolean flag = false;
		
		for(int i=0; i<list.size(); i++){
			if(key == list.get(i).key){
				list.remove(i);
				flag = true;
			}
		}
		if(flag == false)
			array[hascode].add(e);
		else{
			array[hascode].add(e);
		}
	}

	private void printValues() {
		// TODO Auto-generated method stub
		for(int i=0; i<array.length; i++){
			System.out.println("Values of Array[" + i +"]");
			for(int j=0; j<array[i].size(); j++){
				System.out.println(array[i].get(j).key + "," + array[i].get(j).value);
			}
		}
	}

	private int convertTOHasCode(int key) {
		// TODO Auto-generated method stub
		return key % 10;
	}
}

 class Element{
	 int key;
	 String value;
 }